//export const BEFORE_ADD_SEDE = "BEFORE_ADD_SEDE";

export const FETCH_SEDES = "FETCH_SEDES";
export const FETCH_SEDES_SUCCESS = "FETCH_SEDES_SUCCESS";
export const FETCH_SEDES_FAIL = "FETCH_SEDES_FAIL";

export const VALIDATE_PASSWORD = 'VALIDATE_PASSWORD';
export const VALIDATE_PASSWORD_SUCCESS = 'VALIDATE_PASSWORD_SUCCESS';
export const VALIDATE_PASSWORD_FAIL = 'VALIDATE_PASSWORD_FAIL';

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const SELECT_MENU_ITEM = 'SELECT_MENU_ITEM';
export const SELECT_USER_ACTION_ITEM = 'SELECT_USER_ACTION_ITEM';
export const SET_USER_MODAL_STATE = 'SET_USER_MODAL_STATE';
