//export const BEFORE_ADD_SEDE = "BEFORE_ADD_SEDE";

export const FETCH_SEDES = "FETCH_SEDES";
export const FETCH_SEDES_SUCCESS = "FETCH_SEDES_SUCCESS";
export const FETCH_SEDES_FAIL = "FETCH_SEDES_FAIL";
export const FETCH_SEDE = "FETCH_SEDE";
export const FETCH_SEDE_SUCCESS = "FETCH_SEDE_SUCCESS";
export const FETCH_SEDE_FAIL = "FETCH_SEDE_FAIL";
export const SELECT_SEDE_ACTION_ITEM = 'SELECT_SEDE_ACTION_ITEM';
export const SET_SEDES_MODAL_STATE = 'SET_SEDE_MODAL_STATE';
export const SAVE_SEDE = 'SAVE_SEDE';
export const SAVE_SEDE_SUCCESS = 'SAVE_SEDE_SUCCESS';
export const SAVE_SEDE_FAIL = 'SAVE_SEDE_FAIL';

export const VALIDATE_PASSWORD = 'VALIDATE_PASSWORD';
export const VALIDATE_PASSWORD_SUCCESS = 'VALIDATE_PASSWORD_SUCCESS';
export const VALIDATE_PASSWORD_FAIL = 'VALIDATE_PASSWORD_FAIL';

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const SELECT_USER_ACTION_ITEM = "SELECT_USER_ACTION_ITEM";
export const SET_USER_MODAL_STATE = "SET_USER_MODAL_STATE";

export const SELECT_MENU_ITEM = 'SELECT_MENU_ITEM';


export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
